### ISSUE TITLE
请求微信公众号文章列表和单个文章的实例或文档？

### ISSUE THREAD

**Issue by vincent4j** [qingmang-team/docs#11]

**Comment by duguguiyu** [comment]
* 公众号在我们这里都有一个 category id，比如 a1，那用 article.list?category_id=a1 就可以拿到全部的文章，每个文章有 article id，比如 b2，用 article.get?id=b2 就可以拿到正文等其它信息
* 可以访问什么 category，我们有权限控制，可以通过 category.list 查看被授权的全部源站

更多详情，可以参见文档，谢谢。

**Comment by duguguiyu** [comment]
你可以联系 hello@qingmang.me 索取 app key：）

**Comment by vincent4j** [comment]
已经邮件申请。
