### ISSUE TITLE
app.get 未实现

### ISSUE THREAD

**Issue by duguguiyu** [qingmang-team/docs#2]
现在抛 500

**Comment by passos** [comment]
done

```
$ curl 'http://api.qingmang.me/v2/app.get?appid=18763352-9c5b-4a08-9050-60bab4453c23&ts=1491038197&sign=a2baeb43d510249884a41785a4d7026d5c7c01c2'
{"ok":true,"app":{"desc":"quark demo api","name":"quark","id":"18763352-9c5b-4a08-9050-60bab4453c23"}}
```

**Comment by duguguiyu** [comment]
@passos 有个问题，现在是用了 id 什么的，这个接口最好用 token 来做为参数，因为其目的是为了校验 token 是否过期

**Comment by passos** [comment]
想了一下 app.get 还是放到后面去做比较好，因为在网关这一层现有的接口没法直接用 token 反查是否有效，需要 appid 才行。如果放到后面做的话，请求到达说明 token 有效，并且 header 里面会有 APP id 和 username，直接取出返回就好了。

现在这个接口的实现改成 app.id 了，用来获取 app  id 对应的 app 信息。
