### ISSUE TITLE
Duplicate API key found

### ISSUE THREAD

**Issue by chowaikong** [qingmang-team/docs#22]
在 hasMore 为 true 的 response，我使用 nexrUrl 获取下一页返回
```json
{
    "message": "Duplicate API key found"
}
```
请问这是什么问题？另外，为什么错误不是按照文档说明放在 error，而是 message？开发环境可以看到具体 json 内容，在正式环境就不知道应该显示 error 还是 message 了，这令人困惑。

**Comment by guoronghua** [comment]
求下一页的时候不需要再带上 token字段了，下一页的链接里已经有了
