### ISSUE TITLE
想采访一下为啥要提出这个RAML格式

### ISSUE THREAD

**Issue by nomagick** [qingmang-team/docs#25]
基于这个格式，丢失了HTML里面大量的样式信息， 
文章排版给人的感觉整个怪怪的。。。

而且文章的作者很难去影响改善这个效果。。

采访你们一下，这么做是出于什么考虑。。

而且这个格式根本不是一个ML好嘛。。

**Comment by junyu** [comment]
https://en.wikipedia.org/wiki/Markup_language
